#!/bin/sh
clear
nl ~/simple-feed/urls
printf "Enter Choice: "
read -r selected_feed
sed -n "${selected_feed}p" ~/simple-feed/urls | cut -d "|" -f 2 | cut -d " " -f 2 | xargs -r -I {} curl "{}" | grep "<title\|<link" > ~/simple-feed/feed.txt
clear
grep "<title" ~/simple-feed/feed.txt | sed 's/<title*>/\n/g' | sed 's/<\/title*>//g' | awk 'NF' | nl | tac
printf "Enter Choice: "
read -r selected_entry
if [ "$selected_entry" != "" ]
then
	link=$(grep "<link" ~/simple-feed/feed.txt | grep http | sed 's/http/\nhttp/g' | grep ^http | sed 's/\(^http[^ <]*\)\(.*\)/\1/g' | sed 's/"\/>//g' | sed 's/]]>//g' | grep -v channel_id | sed -n "${selected_entry}p")
	nl ~/simple-feed/app.txt
	printf "Enter Choice: "
	read -r selected_app
	app=$(sed -n "${selected_app}p" ~/simple-feed/app.txt)
	$app "$link" &
fi
clear
